services:
  laravel-app:
    build:
      context: ./backend
      args:
        UID: "${UID}"
        GID: "${GID}"
    user: "${UID}:${GID}"
    container_name: laravel-app
    volumes:
      - ./backend:/var/www
    expose:
      - 9000
    networks:
      - shopnet


  # composer:
  #   user: "${UID}:${GID}"
  #   build:
  #     context: dockerfiles
      
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      - shopnet

  react-app:
    build:
      context: ./frontend
    container_name: react-app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - shopnet

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - shopnet

networks:
  shopnet:

volumes:
  db_data: